---
abstract: 'Bringing the power of POE to CPAN smoke testing.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Spec: 0
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-CPAN-Reporter
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
provides:
  POE::Component::CPAN::Reporter:
    file: lib/POE/Component/CPAN/Reporter.pm
    version: 0.06
requires:
  POE: 1.0002
  POE::Component::SmokeBox::Recent: 1
  POE::Wheel::Run: 0
  Storable: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-component-cpan-reporter/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-cpan-reporter.git
version: 0.06
